/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import com.raven.chart.ModelChart;
import java.awt.Color;

/**
 *
 * @author RAVEN
 */
public class BaoCaoThang extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public BaoCaoThang() {
        initComponents();
        getContentPane().setBackground(new Color(250, 250, 250));
        chart.addLegend("1", new Color(245, 189, 135));
        chart.addLegend("2", new Color(135, 189, 245));
        chart.addLegend("3", new Color(189, 135, 245));
        chart.addLegend("4", new Color(139, 229, 222));
        chart.addLegend("5", new Color(139, 229, 222));
        chart.addLegend("6", new Color(139, 229, 222));
        chart.addLegend("7", new Color(139, 229, 222));
        chart.addLegend("8", new Color(139, 229, 222));
        chart.addLegend("9", new Color(139, 229, 222));
        chart.addLegend("10", new Color(139, 229, 222));
        chart.addLegend("11", new Color(139, 229, 222));
        chart.addLegend("12", new Color(139, 229, 222));
        chart.addLegend("13", new Color(139, 229, 222));
        chart.addLegend("14", new Color(139, 229, 222));
        chart.addLegend("15", new Color(139, 229, 222));
        chart.addLegend("16", new Color(139, 229, 222));
        chart.addLegend("17", new Color(139, 229, 222));
        chart.addLegend("18", new Color(139, 229, 222));
        chart.addLegend("19", new Color(139, 229, 222));
        chart.addLegend("20", new Color(139, 229, 222));
        chart.addLegend("21", new Color(139, 229, 222));
        chart.addLegend("22", new Color(139, 229, 222));
        chart.addLegend("23", new Color(139, 229, 222));
        chart.addLegend("24", new Color(139, 229, 222));
        chart.addLegend("25", new Color(139, 229, 222));
        chart.addLegend("26", new Color(139, 229, 222));
        chart.addLegend("27", new Color(139, 229, 222));
        chart.addLegend("28", new Color(139, 229, 222));
        chart.addLegend("29", new Color(139, 229, 222));
        chart.addLegend("30", new Color(139, 229, 222));
        chart.addLegend("31", new Color(139, 229, 222));
        chart.addData(new ModelChart("January", new double[]{500, 200, 80,89, 200, 80,89, 200, 80,89, 200, 80,89, 200, 80,89,200, 80,89, 200,500, 200, 80,89, 200, 80,89, 200, 80,89, 200}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chart = new com.raven.chart.Chart();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biểu đồ báo cáo tháng");

        chart.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        chart.setPreferredSize(new java.awt.Dimension(1000, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoCaoThang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.chart.Chart chart;
    // End of variables declaration//GEN-END:variables
}
